site_name: PUMA

repo_name: "2021-2-PUMA-Doc"
repo_url: "https://github.com/fga-eps-mds/2021-2-PUMA-Doc"

# page structure
nav:
  - Home: index.md
  - Planejamento:
      - Plano de Comunicação: planejamento/plano-comunicacao.md
      - Estrutura Analítica do Projeto: planejamento/eap.md
      - Quadro de Disponibilidade: planejamento/quadro-disponibilidade.md
      - Quadro de Conhecimentos: planejamento/quadro-conhecimentos.md
      - Agenda da Lean Inception: planejamento/lean-inception.md
      - Políticas de Contribuição: planejamento/contribuicao.md
      - Plano de Gerenciamento de Custos: planejamento/plano-custos.md
      - Plano de Gerenciamento de Riscos: planejamento/plano-riscos.md
  - Visão de Produto:
      - Canvas Lean Inception: produto/canvas-li.md
      - Backlog do Produto: produto/backlog.md
      - Documento de Arquitetura: produto/arquitetura.md
      - Protótipo de Alta Fidelidade: produto/prototipo-alta.md
      # - Guia de Estilo e Identidade Visual
  # - Resultados
  - Sprints:
      - Sprint 1:
          Planejamento: sprints/planning-1.md
          Resultados: sprints/review-1.md

# configuration
theme:
  name: material
  custom_dir: material
  language: pt
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.expand
  font:
    text: Poppins
    code: Roboto Mono
  logo: assets/images/puma_favicon.svg
  favicon: assets/images/puma_favicon.svg

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/styles.css
